name: Frontend | Build | WebApp Deployment

run-name: Frontend Build and Deploy • ${{ github.ref_name }} • ${{ github.actor }} • ${{ github.run_id }}

on:
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  software_composition_analysis:
    uses: anurag-vj/devops-cicd-actions-workflows-library/.github/workflows/react.js.yaml@main
    with:
      job_name: 'Software Composition Analysis (Dependency Security)'
      runs_on: 'ubuntu-latest'
      node_version: 16.x
      cache: 'npm'
      working_directory: './frontend'

  code_quality_checks:
    uses: anurag-vj/devops-cicd-actions-workflows-library/.github/workflows/code_quality.yaml@main
    needs: software_composition_analysis
    with: 
      job_name: 'Code Quality and Linting'
      runs_on: 'ubuntu-latest'
      node_version: 16.x
      cache: 'npm'
      working_directory: './frontend'

  application_build:
    uses: anurag-vj/devops-cicd-actions-workflows-library/.github/workflows/npm_build.yaml@main
    needs: code_quality_checks
    with:
      job_name: 'Build and Artifact Package'
      runs_on: 'ubuntu-latest'
      node_version: 16.x
      cache: 'npm'
      artifacts_name: reactui-${{ github.run_id }}
      artifacts_path: package
      working_directory: './frontend'

  application_deployment:
    uses: anurag-vj/devops-cicd-actions-workflows-library/.github/workflows/deploy_build.yaml@main
    needs: application_build
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    with:
      job_name: 'Deploy React.JS to Azure Web App'
      runs_on: ubuntu-latest
      artifacts_name: reactui-${{ github.run_id }}
      artifacts_path: package
      web_app_name: 'web-app-todo-application'
